---
- name: clickhouse
  src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"

- name: vector
  src: git@github.com:dvbychkov/vector-role.git
  scm: git
  version: "1.0.1"

- name: lighthouse
  src: git@github.com:dvbychkov/lighthouse-role.git
  scm: git
  version: "1.1.1"
