---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  become: true
  roles:
    - vector

- name: Install lighthouse and Nginx
  hosts: lighthouse
  become: true

  pre_tasks:
    - name: Lighthouse | Install git
      ansible.builtin.apt:  # Изменено с yum на apt
        name: git
        state: present
      when: ansible_pkg_mgr == 'apt'  # Опционально: проверка менеджера пакетов

  roles:
    - lighthouse
